### PR TITLE
Extension framework

### PR DESCRIPTION
**Pull request by xoshilcm**

### CODE REVIEW

**Comment by scerruti** [comment]
The committed .DS_Store files probably shouldn't be included in the repo.

[Google Search on Excluding DS Store files](https://www.google.com/search?q=exclude+ds_store+git&oq=exclude+ds_store&aqs=chrome.0.0j69i57j0l6.6027j1j7&sourceid=chrome&ie=UTF-8)

**Comment by scerruti** [comment]
@jshepin @dasgdre21 Please review the pull request and make comments or give it a thumbs up.

**Review by josephshepin — APPROVED** [review]
looks good!

**Comment by dream-dg** [comment]
I think it looks good 👍

**Pull request merged**
